theme: jekyll-theme-minimal

title: Thomas Guégan
description: Games, rendering and other cool stuff.

logo: assets/img/logo.png

######################################

collections:
  games:
    output: true