theme: jekyll-theme-minimal

title: Thomas Guégan
description: Games and stuff.

logo: assets/img/logo.png

social_icon_size: fa-3x

github: [metadata]

######################################

collections:
  games:
    output: true